Proyecto 1 2018/Proyecto1/Automata/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

app_name = 'Automata'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

Proyecto 1 2018/Proyecto1/Automata/templates/Automata/acc_active_email.html
{% autoescape off %}
Hola {{ user.Usuario}},
Por favor da click en el link para confirmar tu correo,
http://{{ domain }}{% url 'usuario:activate' uidb64=uid token=token %}
{% endautoescape %}

Proyecto 1 2018/Proyecto1/Automata/templates/Automata/analizador.html
{% extends 'usuario/base.html'%}

{% block body2 %}
    <h1>A continuación te muestro tus textos</h1>
    <ul>
        <li>        {% for obj in images %}   {% endfor %}</li><br>
        <li>Data</li><br>
    <h3> A continuación te muestro tus textos</h3>
    </ul>
    {% if error_massage %} 
        <p><strong>{{error_massage}}</strong></p>
    {% endif %}
{% endblock %}

Proyecto 1 2018/Proyecto1/Automata/templates/Automata/base.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

{% block bg %}<link rel="stylesheet" type="text/css" href="/static/Automata/style2.css"/>﻿{% endblock %}

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!--Logo-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-toggle="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'Automata:index' %}">MTS</a>
        </div>
        {% block body1 %}
        <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class=> 
                        <a href="{% url 'Automata:index' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Agregar Texto
                        </a>
                    </li>
                </ul>
                <ul class="nav navbar-nav">
                    <li class=> 
                        <a href="{% url 'Automata:index' %}">
                        <span class="glyphicon glyphicon-scissors" aria-hidden="true"></span>&nbsp;
                        Modificar Datos
                        </a>
                    </li>
                </ul>
        {% endblock %}
            <ul class="nav navbar-nav navbar-right">
                <li class=> 
                    <a href="{% url 'Automata:index' %}">
                    <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp;
                    Ayuda
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class=> 
                    <a href="{% url 'Automata:index' %}">
                    <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp;
                    Contáctanos
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block body2 %}

{% endblock %}

Proyecto 1 2018/Proyecto1/Automata/templates/Automata/detail.html
{% extends 'PE/base.html'%}

{% block body2 %}
    <h1>Bienvenido {{text.Nombres}} {{text.Apellidos}}</h1>
    <h3> MackTechSolutions te Saluda</h3>
    <ul>
        <li>Nombre de Usuario: {{text.Usuario}}</li><br>
        <li>A continuación te presento tus datos</li><br>
        <li>CUI: {{text.CUI}}</li><br>
        <li>Carrera: {{text.Carrera}}</li><br>
        <li>Correo: {{text.Correo}}</li>
    <h3> A continuación te muestro tus textos</h3>
    {%for obj in p%}
    <li> <a href="url">{{obj.Name}}</a></li>
    {% endfor %}
    </ul>
    {% if error_massage %} 
        <p><strong>{{error_massage}}</strong></p>
    {% endif %}
{% endblock %}

Proyecto 1 2018/Proyecto1/Automata/templates/Automata/form-template.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 coll-sm-10">
        <span class="text-danger small">{{ field.errors }}</span>
    </div>
    <label class="control-label col-sm-1">
         {{ field.label_tag }}
         <div class="col-sm-10">
             {{field}}
         </div>
    </label>
</div>
{% endfor %}

Proyecto 1 2018/Proyecto1/Automata/templates/Automata/index.html
{% extends 'Automata/base.html'%}

{% block bg %}<link rel="stylesheet" type="text/css" href="/static/Automata/style.css"/>﻿{% endblock %}

{% block body1 %}
<div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li class=> 
                <a href="{% url 'Automata:index' %}">
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>&nbsp;
                Convertir
                </a>
            </li>
        </ul>
        <ul class="nav navbar-nav">
            <li class=> 
                <a href="{% url 'Automata:index' %}">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;
                    Ingresar
                </a>
            </li>
        </ul>
{% endblock %}

{% block body2 %}
<h3>Bienvenido a MackTechSolutions</h3>
<form method="POST"  action="">
{% csrf_token %} 
    <input type="text" name="handle" value=""><br>
    <input type="submit" value="Submit">
    </form>
    <li>Te muestro tu texto: {{result}}</li><br>
    <li>En cuanto a Thompson</li>
    <li>Estado incial: {{estadoInicial}}</li>
    <li>Número de estados: {{numeroEstados}}</li>
    <li>Función Transición: {{fThompson}}</li>
    <li>En cuanto a AFND:</li>
    <li>Función transición: {{funcionfinal}}</li>
{% endblock %}

Proyecto 1 2018/Proyecto1/Automata/templates/Automata/login.html
{% extends 'usuario/base.html'%}

{% block bg %}<link rel="stylesheet" type="text/css" href="/static/usuario/style.css"/>﻿{% endblock %}

{% block body1 %}
<div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li class=> 
                <a href="{% url 'usuario:index' %}">
                <span class="glyphicon glyphicon-circle-arrow-left" aria-hidden="true"></span>&nbsp;
                Regresar
                </a>
            </li>
        </ul>
{% endblock %}

{% block body2 %}
<h3>Bienvenido a MackTechSolutions</h3>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action=".">
                        {% csrf_token %}
                        <div class="form-group">
                                <div class="col-sm-offset-2 coll-sm-10">
                                    <span class="text-danger small">{{ field.errors }}</span>
                                </div>
                                <label class="control-label col-sm-1">
                                     Nombre Usuario:
                                     <div class="col-sm-10">
                                         {{ form.Usuario }}
                                     </div>
                                </label>
                            </div>
                            <div class="form-group">
                                    <div class="col-sm-offset-2 coll-sm-10">
                                        <span class="text-danger small">{{ field.errors }}</span>
                                    </div>
                                    <label class="control-label col-sm-1">
                                         Contraseña:
                                         <div class="col-sm-10">
                                             {{ form.contrasena }}
                                         </div>
                                    </label>
                                </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">
                                        Ingresar
                                    </button>
                                </div>
                            </div>               
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Proyecto 1 2018/Proyecto1/Automata/templates/Automata/registration_form.html
{% extends 'usuario/base.html'%}

{% block bg %}<link rel="stylesheet" type="text/css" href="/static/usuario/style.css"/>﻿{% endblock %}

{% block body1 %}
<div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li class=> 
                <a href="{% url 'usuario:index' %}">
                <span class="glyphicon glyphicon-circle-arrow-left" aria-hidden="true"></span>&nbsp;
                Regresar
                </a>
            </li>
        </ul>
{% endblock %}

{% block body2 %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action=".">
                        {% csrf_token %}
                        {% include 'usuario/form-template.html' %} 
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">
                                        Guardar
                                    </button>
                                </div>
                            </div>               
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Proyecto 1 2018/Proyecto1/Automata/templates/Automata/textos_form.html
{% extends 'usuario/base.html'%}

{% block bg %}<link rel="stylesheet" type="text/css" href="/static/usuario/style.css"/>﻿{% endblock %}

{% block body1 %}
<div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li class=> 
                <a href="{% url 'usuario:index' %}">
                <span class="glyphicon glyphicon-circle-arrow-left" aria-hidden="true"></span>&nbsp;
                Regresar
                </a>
            </li>
        </ul>
{% endblock %}

{% block body2 %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="." enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'usuario/form-template.html' %} 
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">
                                        Guardar
                                    </button>
                                </div>
                            </div>               
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Proyecto 1 2018/Proyecto1/Automata/templates/Automata/usuarios_form.html
{% extends 'usuario/base.html'%}

{% block bg %}<link rel="stylesheet" type="text/css" href="/static/usuario/style.css"/>﻿{% endblock %}

{% block body1 %}
<div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li class=> 
                <a href="{% url 'usuario:index' %}">
                <span class="glyphicon glyphicon-circle-arrow-left" aria-hidden="true"></span>&nbsp;
                Regresar
                </a>
            </li>
        </ul>
{% endblock %}

{% block body2 %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action=".">
                        {% csrf_token %}
                        {% include 'usuario/form-template.html' %} 
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">
                                        Guardar
                                    </button>
                                </div>
                            </div>               
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}