Practica 1 2018/Misitio/Misitio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^usuario/', include('usuario.urls'))
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.STATIC_ROOT)

Practica 1 2018/Misitio/usuario/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

app_name = 'usuario'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    # usuarioi/registro
    url(r'^registro/$', views.UsuarioCreate.as_view(), name='registro'),
    # usuario/ingreso
    url(r'^ingreso/$', views.LogIn.as_view(), name='ingreso'),
    # página del usuario modificar
    url(r'(?P<pk>.+)/modificar/', views.UsuarioUpdate.as_view(success_url='/usuario/'), name='usuarioEditar'),
    url(r'(?P<pk>.+)/agregartexto/', views.UsuarioTexto.as_view(), name='usuarioCrearTexto'),
    url(r'(?P<pk>.+)/editartexto/', views.UsuarioUpdate.as_view(success_url='/usuario/'), name='usuarioEditarTexto'),
    # info usuario
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate, name='activate'),
    url(r'^(?P<Usuario>.+)/', views.detail, name='detail'),
    
]

Practica 1 2018/Misitio/usuario/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from django.contrib import messages
from django.core.validators import RegexValidator
from django.core.urlresolvers import reverse
from django.core.validators import FileExtensionValidator
# Create your models here.
class Usuarios(models.Model):
    TIPOS_CIENTIFICOS={
        ('Matemático','Matemático'),
        ('Físico','Físico'),
    }
    Usuario=models.CharField(primary_key=True,max_length=20)
    contrasena=models.CharField(max_length=20)
    Carrera=models.CharField(max_length=20,choices=TIPOS_CIENTIFICOS)
    Nombres=models.CharField(max_length=35)
    Apellidos=models.CharField(max_length=35)
    correo_regex=RegexValidator(regex=r'^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$', message="Correo no válido")
    Correo=models.CharField(validators=[correo_regex],unique=True,max_length=60)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{13}$', message="Debes ingresar un número de 13 dígitos")
    CUI=models.CharField(validators=[phone_regex], max_length=17, blank=True)
    EstaActivo=models.CharField(max_length=20,default="No")
    def get_absolute_url(self):
        return reverse('usuario:detail', kwargs={'pk':self.pk})

class Textos(models.Model): 
    Name=models.CharField(max_length=20)
    Tex_id=models.AutoField(primary_key=True)
    Texto=models.FileField(upload_to="archivos", validators=[FileExtensionValidator(allowed_extensions=['pdf', 'pm2'])])

Practica 1 2018/Misitio/usuario/forms.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.forms import ModelForm
from django import forms
from models import Usuarios
from models import Textos


class UserForm(forms.ModelForm):
    contrasena=forms.CharField(widget=forms.PasswordInput)
    class Meta: 
        model=Usuarios
        fields=['Usuario','Carrera', 'Nombres', 'Apellidos', 'Correo', 'CUI','contrasena']  

class TextForm(ModelForm):
    class Meta:
        model=Textos
        fields=['Name','Texto']   

Practica 1 2018/Misitio/usuario/views.py
# -*- coding: utf-8 -*-
import datetime
from flask import request
from models import Usuarios
from models import Textos
from django.views import generic
from django.views.generic import TemplateView
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm
from .forms import TextForm
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.utils import six
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.core.urlresolvers import reverse

a=""
# Create your views here.
class IndexView(TemplateView):
    template_name='usuario/index.html'

def mandarCorreo(username):
    #client_ip = request.META.get('HTTP_X_FORWARDED_FOR') 
    now = datetime.datetime.now()
    mail_subject = 'Notificación de Ingreso'
    message = "Hola tu fecha, hora e ip de ingreso son: "+str(now.day)+"/"+str(now.month)+"/"+str(now.year)+ ", " +str(now.hour)+":"+str(now.minute) #+ ", " #+client_ip           
    to_email=Usuarios.objects.get(pk=username).Correo
    email = EmailMessage(
        mail_subject, message, to=[to_email]
    )
    email.send()

def detail(request,Usuario):
    if a==Usuario: 
        text=get_object_or_404(Usuarios,pk=Usuario)
        p=Textos.objects.all()
        return render(request,'usuario/detail.html',{'text':text,'p':p})
    else: 
        return redirect('usuario:index')

class UsuarioCreate(View):
    form_class=UserForm
    template_name='usuario/registration_form.html'
    def get(self, request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})
    def post(self, request):
        form=self.form_class(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            username=form.cleaned_data['Usuario']
            password=form.cleaned_data['contrasena']
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activa tu cuenta.'
            message = render_to_string('usuario/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })
            to_email=Usuarios.objects.get(pk=username).Correo
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Por favor confirma tu correo para continuar')
        return render(request,self.template_name,{'form':form})

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = Usuarios.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Usuarios.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.EstaActivo="Si"
        user.save()
        global a
        a=user.Usuario
        # return redirect('home')
        mandarCorreo(user.Usuario)
        return redirect('usuario:detail', user.Usuario)
        
    else:
        return HttpResponse('Activation link is invalid!')


class LogIn(View):
    form_class=UserForm
    template_name='usuario/login.html'
    def get(self, request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})
    def post(self, request):
        form=self.form_class(request.POST)
        username = request.POST['Usuario']
        password = request.POST['contrasena']
        try: 
            user=Usuarios.objects.get(pk=username)
            if user.contrasena==password and user.EstaActivo=="Si": 
                global a
                a=username
                mandarCorreo(username)
                return redirect('usuario:detail', username)
            else: 
                return render(request,self.template_name,{'form':form})
        except Usuarios.DoesNotExist: 
            return render(request,self.template_name,{'form':form})
            
class UsuarioUpdate(UpdateView):
    model=Usuarios
    fields=['Carrera', 'Nombres', 'Apellidos', 'Correo', 'CUI','contrasena']




class UsuarioTexto(CreateView):
    form_class=TextForm
    template_name='usuario/textos_form.html'
    def upload(request):
        if request.method == 'POST':
            form = TextForm(request.POST, request.FILES)
            if form.is_valid():
                obj = form.save()
    def get_success_url(self):
            return reverse('usuario:index')

def display_texto_view(request):
    documento = Texto.objects.get(nombre='doc2')
    x_file= open(path +"\media\\archivos\\"+ 'doc2' +".pdf","r")
    data= x_file.read()
    personas=[]
    for i in list:
        personas.append(str(i)+".jpg")
    return render(request, 'usuario/analizador.html', {'data':data, 'images':imagenes})


                

Practica 1 2018/Misitio/usuario/templates/usuario/base.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

{% block bg %}<link rel="stylesheet" type="text/css" href="/static/usuario/style2.css"/>﻿{% endblock %}

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!--Logo-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-toggle="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'usuario:index' %}">MTS</a>
        </div>
        {% block body1 %}
        <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class=> 
                        <a href="{% url 'usuario:usuarioCrearTexto' text.Usuario%}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Agregar Texto
                        </a>
                    </li>
                </ul>
                <ul class="nav navbar-nav">
                    <li class=> 
                        <a href="{% url 'usuario:usuarioEditar' text.Usuario %}">
                        <span class="glyphicon glyphicon-scissors" aria-hidden="true"></span>&nbsp;
                        Modificar Datos
                        </a>
                    </li>
                </ul>
        {% endblock %}
            <ul class="nav navbar-nav navbar-right">
                <li class=> 
                    <a href="{% url 'usuario:ingreso' %}">
                    <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp;
                    Ayuda
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class=> 
                    <a href="{% url 'usuario:ingreso' %}">
                    <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp;
                    Contáctanos
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block body2 %}
{% endblock %}

Practica 1 2018/Misitio/usuario/templates/usuario/index.html
{% extends 'usuario/base.html'%}

{% block bg %}<link rel="stylesheet" type="text/css" href="/static/usuario/style.css"/>﻿{% endblock %}

{% block body1 %}
<div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li class=> 
                <a href="{% url 'usuario:registro' %}">
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>&nbsp;
                Registrame
                </a>
            </li>
        </ul>
        <ul class="nav navbar-nav">
            <li class=> 
                <a href="{% url 'usuario:ingreso' %}">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;
                    Ingresar
                </a>
            </li>
        </ul>
{% endblock %}

{% block body2 %}
<h3>Bienvenido a MackTechSolutions</h3>
<ul><a class="btn btn-primary" href="{% url 'usuario:registro' %}">Registrame</a>
    <a class="btn btn-primary" href="{% url 'usuario:ingreso' %}">Ingresar</a>
</ul>
{% endblock %}