Proyecto Final Algoritmos/MackBlog/MackBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^PE/', include('PE.urls')),
]

Proyecto Final Algoritmos/MackBlog/PE/urls.py
from django.conf.urls import url
from . import views
app_name='PE'

urlpatterns = [
    #/PE/
    url(r'^$', views.index, name='index'),
    #/PE/Problema36
    url(r'^Problema(?P<numero>[0-9]+)/$', views.detail, name='detail')
]

Proyecto Final Algoritmos/MackBlog/PE/models.py
# -*- coding: utf-8 -*-
#the pass of the superuser is pass1234 and the user is admin
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Problemas(models.Model): 
    numero = models.IntegerField(primary_key=True)
    documento=models.FileField()

Proyecto Final Algoritmos/MackBlog/PE/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404
from .models import Problemas
import os
import sys  
import ply.lex as lex
tokens=(
    'Purple',
    'Blue',
    'Red',
    'Integer',
    'Yellow',
    'Menor',
    'Mayor'
)
t_Integer= r'[0-9]+?'
t_Purple= r'(if|for|else|while|return|import|elif)'
t_Blue=r'(and|not|global|[^a-z]in[^a-z]|def|file)'
t_Yellow=r'(range|print|class)'
t_Red=r'(int|str)'
t_Menor=r'<'
t_Mayor=r'>'
def t_error(t):
    t.lexer.skip(1)
lexer=lex.lex()
reload(sys)  
sys.setdefaultencoding('utf8')
# Create your views here.

def index(request):
    all_problems = Problemas.objects.all()
    context= {
        'all_problems': all_problems
    }
    return render(request, 'PE/index.html', context)

def detail(request, numero):
    problema=get_object_or_404(Problemas, pk=numero)
    context=""
    fichero=file(os.path.dirname(os.path.realpath(__file__))+"/static/PE/Problema"+str(numero)+".text","r")
    contador=1
    for line in fichero:
        if line[0]=="#":
            context+=str(contador) +". "+ '<font color="Green">'  +line+ "</font>"
        else:
            lexer.input(line)
            temporal=line
            for tok in lexer:
                if tok.type=='Menor':
                    a= ' &gt '
                    temporal=temporal.replace(tok.value, a)
                if tok.type=='Mayor':
                    a= ' &lt '
                    temporal=temporal.replace(tok.value, a)
            line=temporal
            lexer.input(line)
            temporal=line
            for tok in lexer:
                if tok.type=='Yellow':
                        a='<font color="Yellow">'+tok.value+"</font>"
                        temporal=temporal.replace(tok.value, a)
                if tok.type=='Blue':
                    a='<font color="Blue">'+tok.value+"</font>"
                    temporal=temporal.replace(tok.value, a)
            line=temporal
            lexer.input(line)
            temporal=line
            for tok in lexer:
                if tok.type=='Purple':
                    a='<font color="brown">'+tok.value+"</font>"
                    temporal=temporal.replace(tok.value, a)
                if tok.type=='Integer':
                    a='<font color="Orange">'+str(tok.value)+"</font>"
                    temporal=temporal.replace(tok.value, a)
                if tok.type=='Red':
                    a='<font color="Red">'+tok.value+"</font>"
                    temporal=temporal.replace(tok.value, a)
            context+=str(contador) +". "+ temporal
            contador+=1
    fichero.close()
    return render(request, 'PE/detail'+str(numero)+'.html', {'problema': problema, 'context':context})

Proyecto Final Algoritmos/MackBlog/PE/templates/PE/base.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

{% block bg %}<link rel="stylesheet" type="text/css" href="/static/PE/style2.css"/>﻿{% endblock %}
<!DOCTYPE html>
<html>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!--Logo-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-toggle="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'PE:index' %}">MTS</a>
        </div>
        {% block body1 %}
        <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class=> 
                        <a href="{% url 'PE:index' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Agregar Texto
                        </a>
                    </li>
                </ul>
                <ul class="nav navbar-nav">
                    <li class=> 
                        <a href="{% url 'PE:index' %}">
                        <span class="glyphicon glyphicon-scissors" aria-hidden="true"></span>&nbsp;
                        Modificar Datos
                        </a>
                    </li>
                </ul>
        {% endblock %}
            <ul class="nav navbar-nav navbar-right">
                <li class=> 
                    <a href="{% url 'PE:index' %}">
                    <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp;
                    Ayuda
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class=> 
                    <a href="{% url 'PE:index' %}">
                    <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp;
                    Contáctanos
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% load latexify %}
{% include 'latexify/stylesheets.html' %}
{% include "latexify/scripts.html" %}
{% block body2 %}

{% endblock %}

Proyecto Final Algoritmos/MackBlog/PE/templates/PE/detail.html
{% extends 'PE/base.html'%}

{% block body2 %}
{% endblock %}

Proyecto Final Algoritmos/MackBlog/PE/templates/PE/detail157.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inconsolata">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

{% block bg %}<link rel="stylesheet" type="text/css" href="/static/PE/style2.css"/>﻿{% endblock %}

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!--Logo-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-toggle="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'PE:index' %}">MTS</a>
        </div>
        {% block body1 %}
        <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class=> 
                        <a href="{% url 'PE:index' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Agregar Texto
                        </a>
                    </li>
                </ul>
                <ul class="nav navbar-nav">
                    <li class=> 
                        <a href="{% url 'PE:index' %}">
                        <span class="glyphicon glyphicon-scissors" aria-hidden="true"></span>&nbsp;
                        Modificar Datos
                        </a>
                    </li>
                </ul>
        {% endblock %}
            <ul class="nav navbar-nav navbar-right">
                <li class=> 
                    <a href="{% url 'PE:index' %}">
                    <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp;
                    Ayuda
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class=> 
                    <a href="{% url 'PE:index' %}">
                    <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp;
                    Contáctanos
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% load latexify %}




<head>
        {% include 'latexify/stylesheets.html' %}
        <div class="w3-container" id="where">
                <div class="w3-content" style="max-width:700px">
                  <h1 class="w3-center w3-padding-16"><span class="w3-tag w3-wide"> Problema 157: </span></h1>
        </div>
        </div>

        <div class="w3-container" id="where">
                <div class="w3-content" style="max-width:700px">
                  <h2 class="w3-center">Resolviendo la ecuación difántica {% latexify '\dfrac{1}{a}+\dfrac{1}{b}=\dfrac{p}{10^n}' math_inline=True %} </h2>
        </div>
        </div>

     </head>

<body>

        <div class="w3-container" id="about">
                <div class="w3-content" style="max-width:1200px" >
                  <h5 class="w3-justify"><span class="w3-tag w3-wide">Enunciado</span></h5>
                  <p> Considere la ecuación diofántica {% latexify '\dfrac{1}{a}+\dfrac{1}{b}=\dfrac{p}{10^n}' math_inline=True %} con a, b, p, n enteros positivos y a ≤ b.</p>
                  <p>¿Cuántas soluciones tiene esta ecuación para 1 ≤ n ≤ 9?</p> 
                    <h5 class="w3-justify"><span class="w3-tag w3-wide">Solución</span></h5>
                    <p>Resolver el problema es notar que el problema original es igual a encontrar las soluciones para (a,b) primos relativos tales que a*b sea divisor de {% latexify '10^n' math_inline=True %}. Luego a partir del valor de (a,b) encontrar el valor de p. Finalmente la cantidad de soluciones extras es lo mismo que la cantidad de divisores de p. 
                    </p>
                    <p>Por ejemplo para n=2, notemos que a=5, b=2, p=70 es solución. Luego, a=2*5, b=2*2, p=70/2, también será solución, y así para cada posible divisor de p. Note luego que cualquier otra solución sigue el mismo patrón, para cualquier solución donde (a,b) no sean primos relativos. Se puede tomar factor común mcd(a,b) y luego multiplicar a p por dicho valor para formar una solución donde (a,b) son primos relativos. El hecho de que a*b debe dividir a {% latexify '10^n' math_inline=True %} se deja como ejercicio para el lector.</p>
                    <p>El algoritmo, entonces debe contar cuantos primos relativos hay tales que (a,b) sean divisores de una potencia de 10, y que (a,b) sean primos relativos, y luego por cada solución, verificar cuantas se forman al factorizar p.</p>
                    <p>La primera parte se encarga de encontrar todos los primos relativos a potencias de dos. (Como a*b debe divir a una potencia de 10 b debe ser múltiplo de 5), luego hace la suma, dado que {% latexify 'p=\dfrac{10^n(a+b)}{ab}' math_inline=True %}, a cada solución le suma, la cantidad de divisores que tiene p. </p>
                    <p>La segunda parte hace lo mismo que la primera, pero ahora busca primos relativos a potencias de cinco.</p>
                    <p>La tercera parte finalmente, hace lo mismo que las anteriores pero para primos relativos a 1 y que dividan a una potencia de 10.</p> 
                    <h5 class="w3-justify"><span class="w3-tag w3-wide">Código</span></h5>
                  <div class="w3-panel w3-leftbar w3-light-grey">
                    <p><pre>{{context|safe}}</pre> </p>
                  </div>
                  <h5 class="w3-justify"><span class="w3-tag w3-wide">Análisis del algoritmo</span></h5>
                  <p>En cuanto al análisis, notemos que las tres partes están dentro de un ciclo for inicial. Hablaremos más al repecto más tarde. 
                    Hablemos ahora de la tercera parte. Esta comienza con un ciclo while, seguido de otros dos cilcos while anidados. Finalmente un ciclo for, que envía a otra función que también es un ciclo for.
                    Son 5 bucles y cada uno tiene sus propias instruciones. Si {% latexify '\\mathcal{O}(n)' math_inline=True %} es lo que tarda el ciclo for con mayor cantidad de números. Entonces {% latexify '\mathcal{O}(n^5)' math_inline=True %}. Es lo que toma esta parte en ejecutarse.
                  </p>
                  <p>Las partes 1 y 2 son idénticas, por lo que ejecutar ambas es como que solamente ejecutáramos una de las dos, dos veces. Además ambas se componen de 4 bucles anidados. Y afuera tienen otro bucle más. Por lo que podemos decir que en realidad
                      tenemos que la parte 1, 2 y 3 de nuestro código son idénticas. Como ya estudiamos el tiempo de ejecución de la tercera parte el tiempo de ejecución de las 3 partes combinadas es de {% latexify '\mathcal{O}(3n^5)' math_inline=True %}
                  </p> 
                  <p>Por último, recordemos el cilco for inicial. Este se ejecuta 10 veces, lo malo es que cada n, afecta el tiempo de ejecución de las demás partes. Pero para simplificar el algoritmo, supongamos que para cada n el tiempo de ejecución es igual. Luego
                      como dicho código se ejecuta 10 veces, entonces es lo mismo que decir que el código anterior se tarda {% latexify '\mathcal{O}(30n^5)' math_inline=True %}. Con lo que finalizamos con el análisis de este algoritmo.
                  </p>
                </div>
              </div>


{% include "latexify/scripts.html" %}
</body>

</html>

Proyecto Final Algoritmos/MackBlog/PE/templates/PE/detail186.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inconsolata">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

{% block bg %}<link rel="stylesheet" type="text/css" href="/static/PE/style2.css"/>﻿{% endblock %}

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!--Logo-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-toggle="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'PE:index' %}">MTS</a>
        </div>
        {% block body1 %}
        <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class=> 
                        <a href="{% url 'PE:index' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Agregar Texto
                        </a>
                    </li>
                </ul>
                <ul class="nav navbar-nav">
                    <li class=> 
                        <a href="{% url 'PE:index' %}">
                        <span class="glyphicon glyphicon-scissors" aria-hidden="true"></span>&nbsp;
                        Modificar Datos
                        </a>
                    </li>
                </ul>
        {% endblock %}
            <ul class="nav navbar-nav navbar-right">
                <li class=> 
                    <a href="{% url 'PE:index' %}">
                    <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp;
                    Ayuda
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class=> 
                    <a href="{% url 'PE:index' %}">
                    <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp;
                    Contáctanos
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% load latexify %}




<head>
        {% include 'latexify/stylesheets.html' %}
        <div class="w3-container" id="where">
                <div class="w3-content" style="max-width:700px">
                  <h1 class="w3-center w3-padding-16"><span class="w3-tag w3-wide"> Problema 186: </span></h1>
        </div>
        </div>

        <div class="w3-container" id="where">
                <div class="w3-content" style="max-width:700px">
                  <h2 class="w3-center">Conexiones de una Red </h2>
        </div>
        </div>

     </head>

<body>

        <div class="w3-container" id="about">
                <div class="w3-content" style="max-width:1200px" >
                  <h5 class="w3-justify"><span class="w3-tag w3-wide">Enunciado</span></h5>
                  <p>Aquí están los registros de un sistema telefónico ocupado con un millón de usuarios</p>
                  {% load static %}
                  <img src="{% static "PE/Registros.jpg" %}" alt="My image"> <br>
            <p> El número de teléfono del que llama y al que llama en el registro {% latexify 'n' math_inline=True %} son {% latexify 'Caller(n) = S_{2n-1}' math_inline=True %}  y  {% latexify 'Called(n) = S_{2n}' math_inline=True %} donde {% latexify 'S_{1,2,3,...}' math_inline=True %} vienen del "Generador de Fibonacci Retrasado":</p>
                    <li>Para {% latexify '1 \leq k \leq 55' math_inline=True %}, {% latexify 'S_k = [100003 - 200003k + 300007k^3]' math_inline=True %} (módulo 1000000)</li>
                    <li>Para {% latexify 'k \leq 56' math_inline=True %}, {% latexify 'S_k = [S_{k-24}+S_{k-55}]' math_inline=True %} (módulo 1000000)<br></li> 
                    <p> Si  {% latexify 'Caller(n) = Called(n)' math_inline=True %} luego se asume que el usuario se confundió y se descarta la llamada; de otra manera la llamada es exitosa.</p>
                    <p>Desde el inicio de los registros decimos que cualquier pareja de usuarios X y Y son amigos si X llama a Y o viceversa. De manera similar, X es amigo del amigo de Z si X es amigo de Y y Y es amigo de Z; y así para cadenas más largas. </p>
                    <p>El número del primer ministro es 524287. ¿Después de cuántas llamadas exitosas, sin contar errores, el 99% de los usuarios (incluyendo el PM) serán amigos, o amigo de un amigo, etc., del Primer Ministro?</p>
                    <h5 class="w3-justify"><span class="w3-tag w3-wide">Solución</span></h5>
                    <p>La idea principal es utilizar el algoritmo Unión-Buscar. Lo que hace es que cada vez que alguien llame a alguna persona, asigna a cada uno un padre.
                        Luego cuando dos conjuntos disjuntos (dos grupos de amigos) se llaman, entonces se juntan, poniendo como padre, al padre del conjunto de mayor longitud. (Si ya pertenecian al mismo conjunto entonces no hace nada)
                    </p>
                    <p>Finalmente en cuanto el conjunto donde esté el Primer Ministro contenga al menos 990000 personas. Entonces el algoritmo se detiene, y como respuesta da el número de llamadas exitosas.</p>
                    <h5 class="w3-justify"><span class="w3-tag w3-wide">Código</span></h5>
                  <div class="w3-panel w3-leftbar w3-light-grey">
                    <p><pre>{{context|safe}}</pre> </p>
                  </div>

                  <h5 class="w3-justify"><span class="w3-tag w3-wide">Análisis del algoritmo</span></h5>
                  <p>La complejidad de este algoritmo está bastante estudiada. Como bien se cita en <a href="https://en.wikipedia.org/wiki/Disjoint-set_data_structure">wikipedia</a> (Sí, la palabra anterior es un link). El tiempo que se tarde el código es lo mismo que el tiempo en el que se ejecuten al menos 2325629 uniones (la cantidad de uniones hechas para que 99% sean amigos), donde el tiempo de ejcución de cada operación es de 
                    {% latexify '\mathcal{O}(\alpha(n))' math_inline=True %} Donde {% latexify '\alpha(n)' math_inline=True %} es la función Ackerman Inversa.</p>
                    <p>Más el tiempo que se tarda en generar los dos números del registro. Digamos {% latexify '\Theta_1(m)' math_inline=True %} (Donde {% latexify '\Theta_1(1)' math_inline=True %} es lo que tarda en generar un registro).</p> 
                    <p>Más el tiempo en que se tarda en generar los 1000000 de nodos inciciales. Esto es {% latexify '\Theta_2(m_2)' math_inline=True %}. Donde {% latexify '\Theta_2(1)' math_inline=True %} es lo que tarda en generar un nodo. (Note que tanto el código para generar un Nodo, como para generar un registro son líneales)</p>
                    <p> En total, toma {% latexify '\mathcal{O}(\alpha (n))+\Theta_1 (m)+\Theta_2 (m_2)' math_inline=True %} en ejecutarse el código.</p> 
                </div>
              </div>


{% include "latexify/scripts.html" %}
</body>

</html>

Proyecto Final Algoritmos/MackBlog/PE/templates/PE/detail36.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inconsolata">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

{% block bg %}<link rel="stylesheet" type="text/css" href="/static/PE/style2.css"/>﻿{% endblock %}

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!--Logo-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-toggle="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'PE:index' %}">MTS</a>
        </div>
        {% block body1 %}
        <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class=> 
                        <a href="{% url 'PE:index' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Agregar Texto
                        </a>
                    </li>
                </ul>
                <ul class="nav navbar-nav">
                    <li class=> 
                        <a href="{% url 'PE:index' %}">
                        <span class="glyphicon glyphicon-scissors" aria-hidden="true"></span>&nbsp;
                        Modificar Datos
                        </a>
                    </li>
                </ul>
        {% endblock %}
            <ul class="nav navbar-nav navbar-right">
                <li class=> 
                    <a href="{% url 'PE:index' %}">
                    <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp;
                    Ayuda
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class=> 
                    <a href="{% url 'PE:index' %}">
                    <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp;
                    Contáctanos
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% load latexify %}




<head>
        {% include 'latexify/stylesheets.html' %}
        <div class="w3-container" id="where">
                <div class="w3-content" style="max-width:700px">
                  <h1 class="w3-center w3-padding-16"><span class="w3-tag w3-wide"> Problema 36: </span></h1>
        </div>
        </div>

        <div class="w3-container" id="where">
                <div class="w3-content" style="max-width:700px">
                  <h2 class="w3-center">Palíndromos en dos Bases </h2>
        </div>
        </div>

     </head>

<body>

        <div class="w3-container" id="about">
                <div class="w3-content" style="max-width:900px" >
                  <h5 class="w3-justify"><span class="w3-tag w3-wide">Enunciado</span></h5>
                  <p>El número decimal, {% latexify '505= 1001001001_2' math_inline=True %} (binario), es palínodromo en ambas bases<br>Encuentre la suma de todos los número,
                    menores que un millón, que sean palíndromos en base 10 y en base 2.</p>
                    <h5 class="w3-justify"><span class="w3-tag w3-wide">Solución</span></h5>
                    <p>El codigo que resuelve este problema consta de 3 partes. La primera se encarga de verificar si el número ingresado es palíndromo o no. La 
                        segunda, pasará el número a binario y finalmente la tercera parte se encargará de verificar si el número en binario también es palíndromo o no. Si es palindromo lo suma 
                        y  si no lo es pasa al siguiente número.
                    </p>

                    <h5 class="w3-justify"><span class="w3-tag w3-wide">Código</span></h5>
                  <div class="w3-panel w3-leftbar w3-light-grey">
                    <p><pre>{{context |safe}}</pre></p>
                  </div>
                  <h5 class="w3-justify"><span class="w3-tag w3-wide">Análisis del algoritmo</span></h5>
                  <p>En cuanto al análisis del tiempo de ejecución, digamos que la sentencia que está dentro del tercer ciclo for toma  {% latexify '\\mathcal{O}(1)' math_inline=True %}
                      en ejecutarse, como estas lineas están dentro de un ciclo, se ejecutarán n veces esto es {% latexify '\\mathcal{O}(n)' math_inline=True %}. Posteriormente, tenemos otro conjunto de k instrucciones. Y finalmente 2 ciclos for anidados. Esto hace que sean 3 ciclos for anidados dando una complejidad de 
                      {% latexify '\\mathcal{O}(n^3)' math_inline=True %}.
                    </p>
                </div>
              </div>


{% include "latexify/scripts.html" %}
</body>

</html>

Proyecto Final Algoritmos/MackBlog/PE/templates/PE/index.html
{% extends 'PE/base.html'%}

{% block bg %}<link rel="stylesheet" type="text/css" href="/static/PE/style.css"/>﻿{% endblock %}

{% block body1 %}
<div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li class=> 
                <a href="{% url 'PE:index' %}">
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>&nbsp;
                Convertir
                </a>
            </li>
        </ul>
        <ul class="nav navbar-nav">
            <li class=> 
                <a href="{% url 'PE:index' %}">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;
                    Ingresar
                </a>
            </li>
        </ul>
{% endblock %}

{% block body2 %}
<h3>Bienvenido a MackBlog</h3>
{% for problema in all_problems %}
<li><a href="{% url 'PE:detail' problema.numero%}"> Problema {{ problema.numero }}</a></li>
{% endfor %}
{% endblock %}